Repository Trip-Record/Server, pull requests merged in 2024-02, with the labels that each got.

#58 [FIX] 일정 단건 조회 API User TripStyle 관련 예외 처리 추가
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
  src/main/java/com/triprecord/triprecord/user/dto/response/UserProfile.java
Labels: fix

#63 [FEAT] 월별 랭킹 조회 API
  src/main/java/com/triprecord/triprecord/location/PlaceService.java
  src/main/java/com/triprecord/triprecord/location/controller/RankController.java
  src/main/java/com/triprecord/triprecord/location/dto/PlaceRankGetResponse.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
Labels: feature

#66 [FEAT] 기록 좋아요 취소 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/service/RecordLikeService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#71 [FEAT] 일정 좋아요 등록 API
  src/main/java/com/triprecord/triprecord/global/config/SecurityConfig.java
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleLikeRepository.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleLikeService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#73 [FEAT] 일정 좋아요 취소 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleLikeService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#80 [FEAT] 일정 댓글 수정 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/request/ScheduleCommentContentRequest.java
  src/main/java/com/triprecord/triprecord/schedule/entity/ScheduleComment.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleCommentService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#82 [FEAT] 일정 댓글 삭제 API
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleCommentService.java
Labels: feature

#85 [FIX] 응답 데이터에 유저 좋아요 전송 여부 추가
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/controller/response/RecordResponse.java
  src/main/java/com/triprecord/triprecord/record/service/RecordLikeService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleLikeService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: fix

#77 [FEAT] 일정 댓글 생성 API
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/request/ScheduleCommentContentRequest.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleCommentService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#93 [FEAT] 기록 댓글 생성 API
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/controller/request/RecordCommentContent.java
  src/main/java/com/triprecord/triprecord/record/service/RecordCommentService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#95 [FEAT] 기록 댓글 삭제 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/service/RecordCommentService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#97 [FEAT] 기록 댓글 수정 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordComment.java
  src/main/java/com/triprecord/triprecord/record/service/RecordCommentService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#83 [FEAT] 계절별 랭킹 조회 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/location/PlaceService.java
  src/main/java/com/triprecord/triprecord/location/controller/LocationController.java
  src/main/java/com/triprecord/triprecord/location/controller/RankController.java
  src/main/java/com/triprecord/triprecord/location/dto/PlaceRankGetResponse.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
Labels: feature, fix

#96 [FEAT] 일정 댓글 목록 조회 API
  src/main/java/com/triprecord/triprecord/global/config/SecurityConfig.java
  src/main/java/com/triprecord/triprecord/global/util/EntityBaseTime.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleCommentGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleCommentPageGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleCommentRepository.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleCommentService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#86 [FEAT] 유저의 일정만 불러오는 API
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleInfo.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleRepository.java
  src/main/java/com/triprecord/triprecord/user/controller/UserController.java
  src/main/java/com/triprecord/triprecord/user/dto/response/UserSchedulePageResponse.java
  src/main/java/com/triprecord/triprecord/user/service/UserService.java
Labels: feature

#89 [FEAT] 유저의 기록만 불러오는 API
  src/main/java/com/triprecord/triprecord/record/dto/RecordInfo.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordRepository.java
  src/main/java/com/triprecord/triprecord/user/controller/UserController.java
  src/main/java/com/triprecord/triprecord/user/dto/response/UserRecordPageResponse.java
  src/main/java/com/triprecord/triprecord/user/service/UserService.java
Labels: feature

#100 [FEAT] 여행 스타일 등록 API 구현
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/user/controller/UserController.java
  src/main/java/com/triprecord/triprecord/user/entity/User.java
  src/main/java/com/triprecord/triprecord/user/service/TripStyleService.java
  src/main/java/com/triprecord/triprecord/user/service/UserService.java
Labels: feature

#102 [FIX] 기록 수정 시의 이미지 삭제 방식 변경
  src/main/java/com/triprecord/triprecord/record/controller/request/RecordModifyRequest.java
  src/main/java/com/triprecord/triprecord/record/service/RecordImageService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: fix
