Repository Trip-Record/Server, pull requests merged in 2024-01, with the labels that each got.

#4 [FEAT] 도메인 구현
  src/main/java/com/triprecord/triprecord/basicproflie/BasicProfile.java
  src/main/java/com/triprecord/triprecord/comment/Comment.java
  src/main/java/com/triprecord/triprecord/global/config/JpaAuditingConfig.java
  src/main/java/com/triprecord/triprecord/global/util/EntityBaseTime.java
  src/main/java/com/triprecord/triprecord/like/Like.java
  src/main/java/com/triprecord/triprecord/place/Place.java
  src/main/java/com/triprecord/triprecord/record/Record.java
  src/main/java/com/triprecord/triprecord/recordimage/RecordImage.java
  src/main/java/com/triprecord/triprecord/tripstyle/TripStyle.java
  src/main/java/com/triprecord/triprecord/user/User.java
Labels: feature

#10 [FEAT] 일정 도메인 구현
  src/main/java/com/triprecord/triprecord/schedule/Schedule.java
  src/main/java/com/triprecord/triprecord/schedulecomment/ScheduleComment.java
  src/main/java/com/triprecord/triprecord/scheduledetail/ScheduleDetail.java
  src/main/java/com/triprecord/triprecord/schedulelike/ScheduleLike.java
  src/main/java/com/triprecord/triprecord/scheduleplace/SchedulePlace.java
Labels: feature

#13 [REFACTOR] 패키지 그룹화
  src/main/java/com/triprecord/triprecord/location/entity/Continent.java
  src/main/java/com/triprecord/triprecord/location/entity/Country.java
  src/main/java/com/triprecord/triprecord/location/entity/Place.java
  src/main/java/com/triprecord/triprecord/record/entity/Record.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordComment.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordImage.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordLike.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordPlace.java
  src/main/java/com/triprecord/triprecord/schedule/entity/Schedule.java
  src/main/java/com/triprecord/triprecord/schedule/entity/ScheduleComment.java
  src/main/java/com/triprecord/triprecord/schedule/entity/ScheduleDetail.java
  src/main/java/com/triprecord/triprecord/schedule/entity/ScheduleLike.java
  src/main/java/com/triprecord/triprecord/schedule/entity/SchedulePlace.java
  src/main/java/com/triprecord/triprecord/user/UserService.java
  src/main/java/com/triprecord/triprecord/user/entity/TripStyle.java
  src/main/java/com/triprecord/triprecord/user/entity/User.java
  src/main/java/com/triprecord/triprecord/user/repository/TripStyleRepository.java
  src/main/java/com/triprecord/triprecord/user/repository/UserRepository.java
Labels: refactor

#14 [REMOVE] 필요없는 필드 삭제
  src/main/java/com/triprecord/triprecord/record/entity/Record.java
  src/main/java/com/triprecord/triprecord/schedule/entity/Schedule.java
Labels: fix

#18 [FEAT] S3 파일 업로드 서비스
  build.gradle
  src/main/java/com/triprecord/triprecord/global/config/S3Config.java
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/global/util/S3Service.java
Labels: feature

#22 [FEAT] 기록 생성 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/global/exception/GlobalControllerAdvice.java
  src/main/java/com/triprecord/triprecord/location/PlaceRepository.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/controller/request/RecordCreateRequest.java
  src/main/java/com/triprecord/triprecord/record/entity/Record.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordImage.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordPlace.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordImageRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordImageService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordPlaceService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#31 [FEAT] 공통 응답 메시지
  src/main/java/com/triprecord/triprecord/global/util/ResponseMessage.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
Labels: feature

#24 [FEAT] 일정 생성 API 구현
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/location/PlaceRepository.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/triprecord/triprecord/schedule/dto/request/ScheduleDetailCreateRequest.java
  src/main/java/com/triprecord/triprecord/schedule/entity/ScheduleDetail.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleDetailRepository.java
  src/main/java/com/triprecord/triprecord/schedule/repository/SchedulePlaceRepository.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleRepository.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#34 [REFACTOR] 검증 및 반환 메서드 분리
  src/main/java/com/triprecord/triprecord/location/PlaceService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordPlaceService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
  src/main/java/com/triprecord/triprecord/user/UserService.java
Labels: fix, refactor

#37 [FIX] 이메일 회원가입 API 여행 스타일 관련 로직 제거
  src/main/java/com/triprecord/triprecord/user/UserController.java
  src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
  src/main/java/com/triprecord/triprecord/user/UserService.java
Labels: fix

#39 [FEAT] 일정 단건 조회 API 구현
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleDetailGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/ScheduleGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/dto/response/SchedulePlaceGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleCommentRepository.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleLikeRepository.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleCommentService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleLikeService.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
  src/main/java/com/triprecord/triprecord/user/dto/response/UserProfile.java
Labels: feature

#46 [FIX] 병합 과정에 생긴 오류 해결
  src/main/java/com/triprecord/triprecord/schedule/dto/response/SchedulePlaceGetResponse.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: fix

#41 [FEAT] 기록 삭제 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/global/exception/GlobalControllerAdvice.java
  src/main/java/com/triprecord/triprecord/global/util/S3Service.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordImageRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordImageService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
  src/main/resources/application.properties
Labels: feature

#40 [FEAT] User 정보 조회 API
  src/main/java/com/triprecord/triprecord/record/repository/RecordLikeRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleLikeRepository.java
  src/main/java/com/triprecord/triprecord/schedule/repository/ScheduleRepository.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
  src/main/java/com/triprecord/triprecord/user/controller/UserController.java
  src/main/java/com/triprecord/triprecord/user/dto/request/UserCreateRequest.java
  src/main/java/com/triprecord/triprecord/user/dto/request/UserLoginRequest.java
  src/main/java/com/triprecord/triprecord/user/dto/response/UserInfoGetResponse.java
  src/main/java/com/triprecord/triprecord/user/repository/UserRepository.java
  src/main/java/com/triprecord/triprecord/user/service/UserService.java
Labels: feature

#43 [FEAT] 기록 수정 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/controller/request/RecordModifyRequest.java
  src/main/java/com/triprecord/triprecord/record/dto/RecordUpdateData.java
  src/main/java/com/triprecord/triprecord/record/entity/Record.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordImageRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordImageService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordPlaceService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#32 [FEAT] 일정 삭제 API 구현
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
  src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
Labels: feature

#50 [FIX] Spring Security 사용자 접근 권한 설정 추가
  src/main/java/com/triprecord/triprecord/global/config/SecurityConfig.java
Labels: fix

#51 [FEAT] 기록 단건 조회 API
  src/main/java/com/triprecord/triprecord/location/PlaceBasicData.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/controller/response/RecordResponse.java
  src/main/java/com/triprecord/triprecord/record/dto/RecordImageData.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordCommentRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordLikeRepository.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordPlaceRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordCommentService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordImageService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordLikeService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordPlaceService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#54 [FEAR] 기록에 좋아요 전송하는 API
  src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
  src/main/java/com/triprecord/triprecord/record/controller/RecordController.java
  src/main/java/com/triprecord/triprecord/record/entity/RecordLike.java
  src/main/java/com/triprecord/triprecord/record/repository/RecordLikeRepository.java
  src/main/java/com/triprecord/triprecord/record/service/RecordCommentService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordLikeService.java
  src/main/java/com/triprecord/triprecord/record/service/RecordService.java
Labels: feature

#55 [FEAT] TripStyle 데이터 목록 조회하는 API
  src/main/java/com/triprecord/triprecord/user/controller/TripStyleController.java
  src/main/java/com/triprecord/triprecord/user/controller/UserController.java
  src/main/java/com/triprecord/triprecord/user/dto/response/TripStyleInfo.java
  src/main/java/com/triprecord/triprecord/user/repository/TripStyleRepository.java
  src/main/java/com/triprecord/triprecord/user/service/TripStyleService.java
Labels: feature
